create_LME_cotr_table_cmd = """
    CREATE TABLE IF NOT EXISTS api_lme_cotr (
    date DATE NOT NULL,
    contract TEXT NOT NULL,
    commercial_credit_long FLOAT NOT NULL,
    commercial_credit_short FLOAT NOT NULL,
    commercial_funds_long FLOAT NOT NULL,
    commercial_funds_short FLOAT NOT NULL,
    commercial_other_long FLOAT NOT NULL,
    commercial_other_short FLOAT NOT NULL,
    commercial_undertakings_long FLOAT NOT NULL,
    commercial_undertakings_short FLOAT NOT NULL,
    commercial_directive_long FLOAT NOT NULL,
    commercial_directive_short FLOAT NOT NULL,
    other_credit_long FLOAT NOT NULL,
    other_credit_short FLOAT NOT NULL,
    other_funds_long FLOAT NOT NULL,
    other_funds_short FLOAT NOT NULL,
    other_other_long FLOAT NOT NULL,
    other_other_short FLOAT NOT NULL,
    other_undertakings_long FLOAT NOT NULL,
    other_undertakings_short FLOAT NOT NULL,
    other_directive_long FLOAT NOT NULL,
    other_directive_short FLOAT NOT NULL,
    tot_credit_long FLOAT NOT NULL,
    tot_credit_short FLOAT NOT NULL,
    tot_funds_long FLOAT NOT NULL,
    tot_funds_short FLOAT NOT NULL,
    tot_other_long FLOAT NOT NULL,
    tot_other_short FLOAT NOT NULL,
    tot_undertakings_long FLOAT NOT NULL,
    tot_undertakings_short FLOAT NOT NULL,
    tot_directive_long FLOAT NOT NULL,
    tot_directive_short FLOAT NOT NULL,
    change_commercial_credit_long FLOAT,
    change_commercial_credit_short FLOAT,
    change_commercial_funds_long FLOAT,
    change_commercial_funds_short FLOAT,
    change_commercial_other_long FLOAT,
    change_commercial_other_short FLOAT,
    change_commercial_undertakings_long FLOAT,
    change_commercial_undertakings_short FLOAT,
    change_commercial_directive_long FLOAT,
    change_commercial_directive_short FLOAT,
    change_other_credit_long FLOAT,
    change_other_credit_short FLOAT,
    change_other_funds_long FLOAT,
    change_other_funds_short FLOAT,
    change_other_other_long FLOAT,
    change_other_other_short FLOAT,
    change_other_undertakings_long FLOAT,
    change_other_undertakings_short FLOAT,
    change_other_directive_long FLOAT,
    change_other_directive_short FLOAT,
    change_tot_credit_long FLOAT,
    change_tot_credit_short FLOAT,
    change_tot_funds_long FLOAT,
    change_tot_funds_short FLOAT,
    change_tot_other_long FLOAT,
    change_tot_other_short FLOAT,
    change_tot_undertakings_long FLOAT,
    change_tot_undertakings_short FLOAT,
    change_tot_directive_long FLOAT,
    change_tot_directive_short FLOAT,
    pct_commercial_credit_long FLOAT NOT NULL,
    pct_commercial_credit_short FLOAT NOT NULL,
    pct_commercial_funds_long FLOAT NOT NULL,
    pct_commercial_funds_short FLOAT NOT NULL,
    pct_commercial_other_long FLOAT NOT NULL,
    pct_commercial_other_short FLOAT NOT NULL,
    pct_commercial_undertakings_long FLOAT NOT NULL,
    pct_commercial_undertakings_short FLOAT NOT NULL,
    pct_commercial_directive_long FLOAT NOT NULL,
    pct_commercial_directive_short FLOAT NOT NULL,
    pct_other_credit_long FLOAT NOT NULL,
    pct_other_credit_short FLOAT NOT NULL,
    pct_other_funds_long FLOAT NOT NULL,
    pct_other_funds_short FLOAT NOT NULL,
    pct_other_other_long FLOAT NOT NULL,
    pct_other_other_short FLOAT NOT NULL,
    pct_other_undertakings_long FLOAT NOT NULL,
    pct_other_undertakings_short FLOAT NOT NULL,
    pct_other_directive_long FLOAT NOT NULL,
    pct_other_directive_short FLOAT NOT NULL,
    pct_tot_credit_long FLOAT NOT NULL,
    pct_tot_credit_short FLOAT NOT NULL,
    pct_tot_funds_long FLOAT NOT NULL,
    pct_tot_funds_short FLOAT NOT NULL,
    pct_tot_other_long FLOAT NOT NULL,
    pct_tot_other_short FLOAT NOT NULL,
    pct_tot_undertakings_long FLOAT NOT NULL,
    pct_tot_undertakings_short FLOAT NOT NULL,
    pct_tot_directive_long FLOAT NOT NULL,
    pct_tot_directive_short FLOAT NOT NULL,
    traders_credit TEXT NOT NULL,
    traders_funds TEXT NOT NULL,
    traders_other TEXT NOT NULL,
    traders_undertakings TEXT NOT NULL,
    traders_directive TEXT NOT NULL,
    traders_tot_credit TEXT NOT NULL,
    traders_tot_funds TEXT NOT NULL,
    traders_tot_other TEXT NOT NULL,
    traders_tot_undertakings TEXT NOT NULL,
    traders_tot_directive TEXT NOT NULL,
    PRIMARY KEY (date, contract));"""